# Generated by Django 5.1.7 on 2025-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veranstaltung', models.CharField(max_length=255)),
                ('ort', models.CharField(max_length=255)),
                ('datum', models.DateField()),
                ('uhrzeit', models.TimeField()),
                ('beschreibung', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
    ]
