# Generated by Django 5.1.7 on 2025-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uhrzeit',
        ),
        migrations.AddField(
            model_name='event',
            name='begin_zeit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_zeit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
