# Generated by Django 5.1.7 on 2025-04-04 19:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0002_remove_event_uhrzeit_event_begin_zeit_event_end_zeit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='foto',
        ),
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
