# Generated by Django 5.1.7 on 2025-07-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erfolge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('inhalt', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='erfolge/')),
                ('jahr', models.DateField()),
            ],
        ),
    ]
